##############################################################################
#                                 Main image                                ##
##############################################################################

FROM nvidia/cuda:10.0-devel-ubuntu18.04
# LABEL maintainer "NVIDIA CORPORATION <cudatools@nvidia.com>"
ENV CUDNN_VERSION 7.5.0.56
# LABEL com.nvidia.cudnn.version="${CUDNN_VERSION}"
RUN apt-get update && apt-get install -y --no-install-recommends \
            libcudnn7=$CUDNN_VERSION-1+cuda10.0 \
            libcudnn7-dev=$CUDNN_VERSION-1+cuda10.0 && \
    apt-mark hold libcudnn7 && \
    rm -rf /var/lib/apt/lists/*


##############################################################################
##                                 Python3.7                                ##
##############################################################################

RUN apt update
RUN echo y | apt install python3

RUN apt update
RUN echo y | apt-get install software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa

RUN apt update
RUN echo y | apt-get install python3.6
RUN echo y | apt install python3-pip
# RUN python3 -m pip install --upgrade pip setuptools
RUN python3.6 -m pip install --upgrade pip setuptools

RUN apt update
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.6 1
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1

##############################################################################
##                                  git                                     ##
##############################################################################
RUN apt update
RUN echo y | apt install git

##############################################################################
##                               libraries                                  ##
##############################################################################
RUN pip3 install tensorflow-gpu==1.15.0
RUN pip3 install scipy
RUN pip3 install requests
RUN pip3 install Pillow
RUN pip3 install numpy
RUN pip3 install cython
RUN pip3 install lmdb
RUN pip3 install moviepy
RUN pip3 install opencv-python
RUN pip3 install torch torchvision
RUN pip3 install ninja
RUN pip3 install wandb


##############################################################################
##                            opencv2 error                                 ##
##############################################################################
RUN apt update
RUN echo y | apt install libgl1-mesa-glx
RUN echo y | apt install libglib2.0-0


##############################################################################
##                               CUDA error                                 ##
##############################################################################
ENV export PATH=/usr/local/cuda-10.0/bin:$PATH
ENV export LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib:$LD_LIBRARY_PATH
ENV export LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64:$LD_LIBRARY_PATH
ENV export CUDA_PATH=/usr/local/cuda-10.0
ENV export CUDA_ROOT=/usr/local/cuda-10.0
ENV export CUDA_HOME=/usr/local/cuda-10.0
ENV export CUDA_HOST_COMPILER=/usr/bin/gcc-7.5