##############################################################################
#  for ITC 
##############################################################################

FROM nvidia/cuda:9.0-devel-ubuntu16.04
# LABEL maintainer "NVIDIA CORPORATION <cudatools@nvidia.com>"
ENV CUDNN_VERSION 7.5.0.56
# LABEL com.nvidia.cudnn.version="${CUDNN_VERSION}"
RUN apt-get update && apt-get install -y --no-install-recommends \
            libcudnn7=$CUDNN_VERSION-1+cuda9.0 \
            libcudnn7-dev=$CUDNN_VERSION-1+cuda9.0 && \
    apt-mark hold libcudnn7 && \
    rm -rf /var/lib/apt/lists/*

##############################################################################
##                Python3 & matplotlib & pip & opencv & tf                  ##
##############################################################################

RUN apt update
RUN echo y | apt install python3
RUN echo y | apt install python3-pip
RUN python3 -m pip install --upgrade pip setuptools

RUN pip3 install tensorflow-gpu==1.12.0
RUN pip3 install scipy
RUN pip3 install requests
RUN pip3 install Pillow
# RUN pip3 install scipy==1.3.3
# RUN pip3 install requests==2.22.0
# RUN pip3 install Pillow==6.2.1
RUN pip3 install numpy
RUN pip3 install tensorboard
RUN pip3 install cython
RUN pip3 install lmdb
RUN pip3 install moviepy

RUN pip3 install opencv-python

RUN pip3 install torch==1.1 torchvision==0.3


##############################################################################
##                               pytorch                                    ##
##############################################################################
RUN apt update
RUN echo y | apt install git


##############################################################################
##                            opencv2 error                                 ##
##############################################################################
RUN apt update
RUN echo y | apt install libgl1-mesa-glx
RUN echo y | apt install libglib2.0-0